### ISSUE TITLE
v5.2.7 is found

### ISSUE THREAD

**Issue by masterzorag** [masterzorag/RTL8192EU-linux#8]
Pushed initial unpack
https://github.com/masterzorag/RTL8192EU-linux/tree/v5.2.7?files=1
As seen [here](https://github.com/Mange/rtl8192eu-linux-driver/issues/69)

**Comment by masterzorag** [comment]
We can cherry-pick our patches from already tested work for Realtek v4.4.1 driver so just start clean in a dedicated branch

**Comment by masterzorag** [comment]
Managed to build with linux-4.13.15 and 4.14.7, pushed commits
@gilcu3 @nomadmzl Testing needed
@CGarces patches were ported since they does not apply cleanly: Realtek renamed some debug functions, or reordered defines; review is advised

**Comment by CGarces** [comment]
Consider activate Travis on your repository, it's very usefully to test the current kernel compatibility.
See https://github.com/marketplace

**Comment by gilcu3** [comment]
Right now giving me this compilation error:

```
$ make
...
RTL8192EU-linux/os_dep/linux/ioctl_linux.c:13384:6: error: implicit declaration of function ‘is_compat_task’; did you mean ‘is_idle_task’? [-Werror=implicit-function-declaration]
  if (is_compat_task())
      ^~~~~~~~~~~~~~
      is_idle_task
cc1: some warnings being treated as errors
```



```
# uname -a
Linux pc 4.13.12-1-zen #1 ZEN SMP PREEMPT Wed Nov 8 21:53:04 UTC 2017 x86_64 GNU/Linux
```

**Comment by CGarces** [comment]
@gilcu3 use this fix
https://github.com/CGarces/rtl8189ES_linux/commit/ffcd75359071d044b2bf1c8c741d87a6af104f09

**Comment by gilcu3** [comment]
Now I have tested monitor, station and ap modes, all working ok on kernel 4.14.
On the other side, any of you have tested concurrent mode (described in the docs)? I had tested it with 4.4.1 driver and it worked ok. With this one I get kernel errors and few minutes later computer dies.

**Comment by masterzorag** [comment]
@gilcu3 can you paste which kernel errors you get?
I don't have tested it yet, and not looked at *concurrent mode* at all...

**Comment by gilcu3** [comment]
I will post logs in a few minutes (after freezing my pc and restarting it). In order to compile it in that mode just add `EXTRA_CFLAGS += -DCONFIG_CONCURRENT_MODE` in the corresponding block in Makefile

**Comment by gilcu3** [comment]
(today in different pc the OS didn't freeze but got the same kernel error)
EDIT: had to force reboot after some minutes (mysteriously right after clicking NetworkManager applet to check it was unresponsive)
[https://pastebin.com/qhhcSKNi](https://pastebin.com/qhhcSKNi)
you can find it from line 1823. it occurs right after using one interface in station mode and the other in ap mode.

**Comment by masterzorag** [comment]
hi, @gilcu3 a look at log points me to cfg80211_scan_done, NULL dereference
we have done [a change](https://github.com/masterzorag/RTL8192EU-linux/commit/104f6a65bc69c991961d8797dcd1a6435e4e8ada) there;

**Comment by gilcu3** [comment]
@masterzorag don't really know if that's the reason, nor how to fix it, nor test it :(, do you have any clue?

**Comment by masterzorag** [comment]
Yes, we just patch to get the kernel interface compile fine, but since realtek driver supports just 4.6, we are not dealing with the (now) needed arguments (now we pass &info, but does we have any?)
Or better, there is something other to do with that?

**Comment by gilcu3** [comment]
well, I tested Mange's current branch, that had the same commit, and it worked ok. So, don't think that commit is the issue, unless it's an indirect consequence of it.

**Comment by masterzorag** [comment]
@gilcu3 I am getting issues with linux-4.14.y, I'm stick with 4.13.15
Can you check if does it matters in your test?

**Comment by masterzorag** [comment]
We will need this fix for 4.14.y:
https://github.com/paspro/rtl8812au/commit/3d5117ee85648c663c22228158a8f5f65350ff93

**Comment by CYIYO** [comment]
The patch about cfg80211_scan_done issue is no problem, it doesn't need any other arguments.
8192eu newest formal release is 5.2.19.1.

**Comment by gilcu3** [comment]
@CYIYO where could we get it? 
@masterzorag I will install and test with kernel 4.13 and report back... Did you have issues with concurrent mode or with the normal ones?
EDIT: got the same results with 4.13, after activating both interfaces, kernel error and a few minutes later computer frozen...

**Comment by Mjasnik** [comment]
I'm trying to use this driver for TP Link tl-wn822n v4 on my atom nas, which is AP as well.
For me everything compiles fine w/ kernel 4.4, had to add tp link ids and disable debug. I tried 4.14 as well, for that I used more patches some manually, but now they are referenced in this thread as well.
But with those 2 kernels and multiple driver versions, AP does not work for long. It silently dies, it works for some time, max was one day, usually 15-30 mins.
I suspect this is a power issue.

**Comment by masterzorag** [comment]
@gilcu3 I've moved testing to linux-4.14.7, normal use is working;
The issues I was referring was due compilation but fixed by last commit.
@Mjasnik look at Makefile and try disabling PowerSaving feature, also double check if your chip is 8192eu or another one
Also, is your nas so open to build and run linux-4.14? What does it run, OpenWRT?

**Comment by Mjasnik** [comment]
@masterzorag It's custom built a-lot-of-all-in-one box with 6 network interfaces :)
Driver says:
[279678.156856] RTL871X: CHIP TYPE: RTL8192E
[279678.159157] RTL871X: ReadChipVersion192e 0xF0 = 0xc441935
[279678.159168] RTL871X: Chip Version Info: CHIP_8192E_Normal_Chip_SMIC_B_CUT_2T2R_RomVer(0)

On tp link web site there is very similar driver to this, except it's for kernel 3.10. But as I said this driver works as well. Soon I'll get self powered usb hub to test it out.
I'm interested in @CYIYO comment about even newer version.

**Comment by masterzorag** [comment]
@Mjasnic, I had used connect dongle to an usb hub, selfpowered or not... if just another device I connect makes problem, usb gets resetted and wireless interface stopped working... so, I had  moved dongle connected directly to pc;
And yes, there is a legendary newer version?

**Comment by masterzorag** [comment]
@Mjasnic, I had used connect dongle to an usb hub, selfpowered or not... if just another device I connect makes problem, usb gets resetted and wireless interface stopped working... so, I had  moved dongle connected directly to pc;
And yes, there is a legendary newer version?

**Comment by Mjasnik** [comment]
@masterzorag and others, I have somewhat success with my tplink 822 v4. Actually it did not matter wheter dongle is connected directly to pc or via self powered hub, it might get reset anyway.
So currently I run mac8... drivers, it's stable and running for weeks w/o issues. BUT, as son as I connect my dell laptop running linux to it, it crashes immediately. Android phones - no problems at all. I suspect it's due to ht features. I tried runing realtek drivers rtl871..., with these I can bring up AP but can not connect to it at all.
So it's sorta weird.
How do You run these?
